apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "wordpress-application"
  labels:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/version: 1.0.0
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "wordpress"
  descriptor:
    links:
      - description: "Check Application"
        url: http://54.191.26.84:repl{{ ConfigOption "wp-port" }}
