apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: wordpress-config
spec:
  groups:
    - name: wordpress
      title: Wordpress
      description: Wordpress 
      items:
        - name: wp-port
          title: wordpress port
          type: text
  selector:
    matchLabels:
     app.kubernetes.io/name: "wordpress-mayfly"
  descriptor:
    links:
      - description: "View Repo"
        url: https://github.com/danryan621/kots-wordpress.git
       
